---
kind: Secret
apiVersion: v1
metadata:
  name: cloudflare-ddns
  namespace: default
type: Opaque
data:
  CF_EMAIL:  # base64 value here
  CF_TOKEN:  # base64 value here
  CF_DOMAIN:  # base64 value here
