---
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Simple python
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    # Docker login
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    # Checkout repo
      - uses: actions/checkout@v3

    # Set repository name lowercase in env REPO
      - name: Downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    # Build docker image
      - name: Build docker image
        run: docker build -t ghcr.io/$REPO:latest .

    # Push docker image
      - name: Push docker image
        run: docker push ghcr.io/$REPO:latest
